services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: OColecionadorUser
      RABBITMQ_DEFAULT_PASS: OColecionador@2025
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: OColecionadorUser
      POSTGRES_PASSWORD: OColecionador@2025
      POSTGRES_DB: OColecionadorAugmentationsDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./OColecionadorAugmentations/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: OColecionadorUser
      MINIO_ROOT_PASSWORD: OColecionador@2025
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
