services:
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: sqlserver
      environment:
        SA_PASSWORD: "OColecionador@2025"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
      ports:
        - "1433:1433"
      volumes:
        - sqlserver_data:/var/opt/mssql
      
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlinit
    depends_on:
      - sqlserver
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P OColecionador@2025 -d master -i /init.sql
      "
    volumes:
      - ./OColecionadorBackEnd/init.sql:/init.sql

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: OColecionadorUser
      POSTGRES_PASSWORD: OColecionador@2025
      POSTGRES_DB: OColecionadorAugmentationsDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: OColecionadorUser
      MINIO_ROOT_PASSWORD: OColecionador@2025
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: OColecionadorUser
      RABBITMQ_DEFAULT_PASS: OColecionador@2025

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rabbitmq
      - minio
    ports:
      - "8080:80"

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    environment:
      NGROK_AUTHTOKEN: "31flKxO9PWxmhWVjYTuhnZYzGKl_54r7zVMTMZku3GTK6ADUm"
    command: "http --url=louse-model-lioness.ngrok-free.app nginx:80"
    depends_on:
      - nginx

volumes:
  sqlserver_data:
  postgres_data:
  minio_data:
  
